//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bioinformatics.Buisness.Proxies.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IAntsManager")]
    public interface IAntsManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/GetCurrentAntsSettings", ReplyAction="http://tempuri.org/IAntsManager/GetCurrentAntsSettingsResponse")]
        Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.AntsConfigurationModel> GetCurrentAntsSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/GetCurrentAntsSettings", ReplyAction="http://tempuri.org/IAntsManager/GetCurrentAntsSettingsResponse")]
        System.Threading.Tasks.Task<Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.AntsConfigurationModel>> GetCurrentAntsSettingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/SetAntsSettings", ReplyAction="http://tempuri.org/IAntsManager/SetAntsSettingsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.ProteinNode[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.AntsConfigurationModel>))]
        Bioinformatics.Common.Others.Result SetAntsSettings(Bioinformatics.Buisness.Models.AntsConfigurationModel antsConfiguration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/SetAntsSettings", ReplyAction="http://tempuri.org/IAntsManager/SetAntsSettingsResponse")]
        System.Threading.Tasks.Task<Bioinformatics.Common.Others.Result> SetAntsSettingsAsync(Bioinformatics.Buisness.Models.AntsConfigurationModel antsConfiguration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/GetPositiveNodes", ReplyAction="http://tempuri.org/IAntsManager/GetPositiveNodesResponse")]
        Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.ProteinNode[]> GetPositiveNodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/GetPositiveNodes", ReplyAction="http://tempuri.org/IAntsManager/GetPositiveNodesResponse")]
        System.Threading.Tasks.Task<Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.ProteinNode[]>> GetPositiveNodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/GetNegativeNodes", ReplyAction="http://tempuri.org/IAntsManager/GetNegativeNodesResponse")]
        Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.ProteinNode[]> GetNegativeNodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/GetNegativeNodes", ReplyAction="http://tempuri.org/IAntsManager/GetNegativeNodesResponse")]
        System.Threading.Tasks.Task<Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.ProteinNode[]>> GetNegativeNodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/Start", ReplyAction="http://tempuri.org/IAntsManager/StartResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.ProteinNode[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.AntsConfigurationModel>))]
        Bioinformatics.Common.Others.Result Start();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/Start", ReplyAction="http://tempuri.org/IAntsManager/StartResponse")]
        System.Threading.Tasks.Task<Bioinformatics.Common.Others.Result> StartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/Pause", ReplyAction="http://tempuri.org/IAntsManager/PauseResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.ProteinNode[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.AntsConfigurationModel>))]
        Bioinformatics.Common.Others.Result Pause();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/Pause", ReplyAction="http://tempuri.org/IAntsManager/PauseResponse")]
        System.Threading.Tasks.Task<Bioinformatics.Common.Others.Result> PauseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/Finish", ReplyAction="http://tempuri.org/IAntsManager/FinishResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.ProteinNode[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.AntsConfigurationModel>))]
        Bioinformatics.Common.Others.Result Finish();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/Finish", ReplyAction="http://tempuri.org/IAntsManager/FinishResponse")]
        System.Threading.Tasks.Task<Bioinformatics.Common.Others.Result> FinishAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/GetManagerState", ReplyAction="http://tempuri.org/IAntsManager/GetManagerStateResponse")]
        Bioinformatics.Buisness.Models.ManagerState GetManagerState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/GetManagerState", ReplyAction="http://tempuri.org/IAntsManager/GetManagerStateResponse")]
        System.Threading.Tasks.Task<Bioinformatics.Buisness.Models.ManagerState> GetManagerStateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/GraphBuildStat", ReplyAction="http://tempuri.org/IAntsManager/GraphBuildStatResponse")]
        Bioinformatics.Buisness.Models.StatusEntity GraphBuildStat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAntsManager/GraphBuildStat", ReplyAction="http://tempuri.org/IAntsManager/GraphBuildStatResponse")]
        System.Threading.Tasks.Task<Bioinformatics.Buisness.Models.StatusEntity> GraphBuildStatAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAntsManagerChannel : Bioinformatics.Buisness.Proxies.ServiceRef.IAntsManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AntsManagerClient : System.ServiceModel.ClientBase<Bioinformatics.Buisness.Proxies.ServiceRef.IAntsManager>, Bioinformatics.Buisness.Proxies.ServiceRef.IAntsManager {
        
        public AntsManagerClient() {
        }
        
        public AntsManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AntsManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AntsManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AntsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.AntsConfigurationModel> GetCurrentAntsSettings() {
            return base.Channel.GetCurrentAntsSettings();
        }
        
        public System.Threading.Tasks.Task<Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.AntsConfigurationModel>> GetCurrentAntsSettingsAsync() {
            return base.Channel.GetCurrentAntsSettingsAsync();
        }
        
        public Bioinformatics.Common.Others.Result SetAntsSettings(Bioinformatics.Buisness.Models.AntsConfigurationModel antsConfiguration) {
            return base.Channel.SetAntsSettings(antsConfiguration);
        }
        
        public System.Threading.Tasks.Task<Bioinformatics.Common.Others.Result> SetAntsSettingsAsync(Bioinformatics.Buisness.Models.AntsConfigurationModel antsConfiguration) {
            return base.Channel.SetAntsSettingsAsync(antsConfiguration);
        }
        
        public Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.ProteinNode[]> GetPositiveNodes() {
            return base.Channel.GetPositiveNodes();
        }
        
        public System.Threading.Tasks.Task<Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.ProteinNode[]>> GetPositiveNodesAsync() {
            return base.Channel.GetPositiveNodesAsync();
        }
        
        public Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.ProteinNode[]> GetNegativeNodes() {
            return base.Channel.GetNegativeNodes();
        }
        
        public System.Threading.Tasks.Task<Bioinformatics.Common.Others.DataResult<Bioinformatics.Buisness.Models.ProteinNode[]>> GetNegativeNodesAsync() {
            return base.Channel.GetNegativeNodesAsync();
        }
        
        public Bioinformatics.Common.Others.Result Start() {
            return base.Channel.Start();
        }
        
        public System.Threading.Tasks.Task<Bioinformatics.Common.Others.Result> StartAsync() {
            return base.Channel.StartAsync();
        }
        
        public Bioinformatics.Common.Others.Result Pause() {
            return base.Channel.Pause();
        }
        
        public System.Threading.Tasks.Task<Bioinformatics.Common.Others.Result> PauseAsync() {
            return base.Channel.PauseAsync();
        }
        
        public Bioinformatics.Common.Others.Result Finish() {
            return base.Channel.Finish();
        }
        
        public System.Threading.Tasks.Task<Bioinformatics.Common.Others.Result> FinishAsync() {
            return base.Channel.FinishAsync();
        }
        
        public Bioinformatics.Buisness.Models.ManagerState GetManagerState() {
            return base.Channel.GetManagerState();
        }
        
        public System.Threading.Tasks.Task<Bioinformatics.Buisness.Models.ManagerState> GetManagerStateAsync() {
            return base.Channel.GetManagerStateAsync();
        }
        
        public Bioinformatics.Buisness.Models.StatusEntity GraphBuildStat() {
            return base.Channel.GraphBuildStat();
        }
        
        public System.Threading.Tasks.Task<Bioinformatics.Buisness.Models.StatusEntity> GraphBuildStatAsync() {
            return base.Channel.GraphBuildStatAsync();
        }
    }
}
